---
- name: install dependencies (apt)
  become: yes
  apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present

- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    state: present

- name: install kubectl (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
    state: present

- name: install kubectl (apt)
  become: yes
  apt:
    name: kubectl
    state: present
