---
# - assert: { that: "openshift_oc_version != 'RedHat'" }
- include_tasks: helm.yml
  tags:
    - k8s
- include_tasks: kubectl.yml
  tags:
    - k8s

# Helm - The Kubernetes Package Manager
# https://helm.sh
- name: Installing OpenShift cli
  unarchive:
    src: "{{ openshift_oc_url }}"
    dest: "{{ install_destination }}"
    remote_src: yes
  tags:
    - k8s

- include_tasks: odo.yml
  when: openshift_major_version == "4"
  tags:
    - k8s



